#项目配置
project:
  name: college-entrance
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2023
  # 实例演示开关
  demoEnabled: true
  # 获取ip地址开关
  addressEnabled: true

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy=ant_path_matcher:

logging:
  config: "classpath:log/logback.xml"

# Mybatis配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: false

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  pathMapping: /

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（小时）
  expireTime: 24