server:
  port: 8082

#项目配置
project:
  # 头像，excel等文件路径 (Windows配置D:/uploadPath，Linux配置 /home/uploadPath)
  profile: D:/uploadPath
  # 获取ip地址开关
  addressEnabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://124.223.95.146:3306/example-college-entrance
#    username: root
#    password: f048fac128243533
#    driver-class-name: com.mysql.jdbc.Driver
